config/routes.rb
Rails.application.routes.draw do
  root 'searches#index'

  resources :searches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @searches = Search.all
  end

  def show
    @search = Search.find(params[:id])
  end

  def new
    @search = Search.new
  end

  def edit
    @search = Search.find(params[:id])
  end

  def create
    @search = Search.new(search_params)

    if @search.save
      redirect_to @search
    else
      render 'new'
    end
  end

  def update
    @search = Search.find(params[:id])

    if @search.update(search_params)
      redirect_to @search
    else
      render 'edit'
    end
  end

  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    redirect_to searches_path
  end

  private
  def search_params
    params.require(:search).permit(:name, :query, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Listingalerts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand">BaySniper</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Searches', searches_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Listings</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_with model: @search, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :query %><br>
    <%= form.text_area :query, size: '60x3' %>
  </p>

  <p>
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </p>

  <p>
    <%= form.submit class: 'btn btn-success' %>
  </p>
<% end %>

app/views/searches/edit.html.erb
<h1>Edit search</h1>

<%= render 'form' %>

app/views/searches/index.html.erb
<h1>Searches</h1>

<p>
  <%= link_to 'New search', new_search_path, class: 'btn btn-success' %>
</p>

<% if @searches %>
  <ul>
  <% @searches.each do |search| %>
    <li>
      <span>
        <%= search.query %>
      </span>
      <%= link_to 'View', search_path(search) %>
    </li>
  <% end %>
  </ul>
<% else %>
    <span>No searches added.</span>
<% end %>

app/views/searches/new.html.erb
<h1>New search</h1>

<%= render 'form' %>

app/views/searches/show.html.erb
<h2><%= @search.name %></h2>

<p>
  Query: <%= @search.query %>
</p>

<p>Category: <%= @search.category %></p>

<p>
  <%= link_to 'Edit', edit_search_path(@search), class: 'btn btn-success' %>
  <%= link_to 'Delete', search_path(@search),
              class: 'btn btn-danger',
              method: :delete,
              data: { confirm: 'Delete search?' } %>
</p>